# Veritaban? Ayarlar? (env. variables önceliklidir, yoksa localhost'u kullan?r)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/barber_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration (Canl?da Redis kullan?yorsak bunlar? da environmet variable yapabiliriz..)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# RESILIENCE4J RETRY CONFIGURATION
resilience4j.retry.instances.authRetry.maxAttempts=3
resilience4j.retry.instances.authRetry.waitDuration=2s
resilience4j.retry.instances.authRetry.retryExceptions[0]=org.springframework.dao.QueryTimeoutException
resilience4j.retry.instances.authRetry.retryExceptions[1]=java.sql.SQLException
resilience4j.retry.instances.authRetry.retryExceptions[2]=java.net.ConnectException

# LOGGING
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG